server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: liten-api
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:mariadb://localhost:3306/liten_db?useUnicode=true&characterEncoding=utf8mb4&allowMultiQueries=true
    username: ${DB_USERNAME:liten_user}
    password: ${DB_PASSWORD:liten_password}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        show_sql: false
        default_batch_fetch_size: 100
    show-sql: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope: profile,email
          apple:
            client-id: ${APPLE_CLIENT_ID:}
            client-secret: ${APPLE_CLIENT_SECRET:}

# JWT 설정
jwt:
  secret: ${JWT_SECRET:your-secret-key-change-this-in-production}
  expiration: 86400000 # 24시간 (밀리초)
  refresh-expiration: 604800000 # 7일 (밀리초)

# AWS S3 설정
aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY:}
    secret-key: ${AWS_S3_SECRET_KEY:}
    region: ${AWS_S3_REGION:ap-northeast-2}
    bucket: ${AWS_S3_BUCKET:liten-files}

# 로깅 설정
logging:
  level:
    com.liten.api: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/liten-api.log

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# 앱 특정 설정
app:
  name: 리튼 API
  version: 1.0.0
  cors:
    allowed-origins: 
      - http://localhost:3000
      - http://localhost:8080
      - https://liten-app.com
  file:
    upload-dir: ${FILE_UPLOAD_DIR:./uploads}
    max-size: 100MB

---
# 개발 환경
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:mariadb://localhost:3306/liten_dev_db?useUnicode=true&characterEncoding=utf8mb4
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    com.liten.api: DEBUG

---
# 프로덕션 환경
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: ${DATABASE_URL}
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: WARN
    com.liten.api: INFO